---
clickhouse_syslog_table_query: |
  CREATE TABLE logs.syslogd (
  PRIORITY TINYINT,
  SYSLOG_FACILITY TINYINT,
  SYSLOG_IDENTIFIER String,
  host String,
  message String,
  source_type String,
  timestamp DateTime)
  ENGINE = MergeTree
  ORDER BY timestamp;
clickhouse_listen_host:
  - "::"
clickhouse_dbs_custom:
      - { name: logs }
clickhouse_profiles_default:
  default:
    date_time_input_format: best_effort
clickhouse_networks_default:
  - "::/0"
  - "127.0.0.1"
