- name: Destroy yc instances
  hosts: all
  tasks:
    - name: Destroy created instances
      timych.yandex_cloud_cvl.yc:
        name: "{{ item.name }}"
        state: absent
        zone: ru-central1-a
      register: testout
      loop:
        - name: 'clickhouse-01'
        - name: 'vector-01'
        - name: 'lighthouse-01'
